### ISSUE TITLE
Compatibility with JCE Editor

### ISSUE THREAD

**Issue by soundsessential** [bpextensions/plg_system_bpprettify#3]
Does this work with JCE Editor in Joomla? After installing I don't see the Insert/Edit Code Sample button. Thanks.

**Comment by artur-stepien** [comment]
It is compatible with every editor. JCE too. You add code in PRE tag or CODE. In JCE you can do it by clicking anywhere, change Paragraph (near Style) to Code, and paste your code directly. Thats is one way. TinyMCE works best as it has a button for adding code with textarea input field (then it wraps all in pre/code tag).

**Comment by soundsessential** [comment]
Ah gotcha, yes so it doesn't add a button in JCE but does still work. This is great, thanks. 

One more question, are there any parameters that can be added in the pre tag to format that block with a particular style rather than the default in the settings, or even not use the plugin for this particular pre tag? I don't see any info about that. If there's Google documentation that explains options, please do just point me at that. Thanks again.

**Comment by artur-stepien** [comment]
@soundsessential Yeah, this is just adding a code highlight to an already added code. But adding a custom button in Editor wouldn't be a bad idea. I'll add this to the features and probably implement in a next release. That would simplify usage on some worse editors like JCE. 

As for now, default (set in plug-in settings) style is applied. I'm not sure if while using those themes it will be possible to implement the ability to chose style per block of code.
